import Head from "next/head";
import { Octokit } from "octokit";

export default function Home() {
  const key =
    "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";
  const api = "https://api.github.com/orgs/ORG/repos";
  // Octokit.js
  // https://github.com/octokit/core.js#readme
  const octokit = new Octokit({
    auth: "key",
  });

  const loadData = async () => {
    await octokit.request(`GET /orgs/{org}/repos`, {
      org: "ORG",
      headers: {
        "X-GitHub-Api-Version": "2022-11-28",
      },
    });
  };
  console.log(loadData());
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>dddd</div>
    </>
  );
}
