import Head from "next/head";
import RepoCard from "../components/RepoCard";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import {
  getReposByOrgService,
  getReposByUserNameService,
} from "../services/index";
import styles from "./styles.module.css";
import SearchBar from "@/components/SearchBar";

export default function Home() {
  const router = useRouter();
  const stringSearch = router.query?.search || "";
  const listKeyword = stringSearch.split(" ");
  const [data, setData] = useState([]);
  const [isFetching, setIsFetching] = useState(false);

  const loadData = async () => {
    if (stringSearch) {
      const reposByOrg = await Promise.all(
        listKeyword.map((item) => getReposByOrgService(item.toString()))
      );
      const reposByUsername = await Promise.all(
        listKeyword.map((item) => getReposByUserNameService(item.toString()))
      );
      let listRepo = [];
      listRepo = listRepo.concat.apply(listRepo, reposByOrg);
      listRepo = listRepo.concat.apply(listRepo, reposByUsername);
      setData(listRepo);
    } else {
      setData([]);
    }
  };

  useEffect(() => {
    loadData();
  }, [stringSearch]);

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const handleScroll = () => {
    if (
      window.innerHeight + document.documentElement.scrollTop !==
      document.documentElement.offsetHeight
    )
      return;
    setIsFetching(true);
  };
  console.log(document.documentElement.scrollTop);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className={styles.container}>
          <SearchBar />
          {data.length > 0 &&
            data?.map((item) => {
              const {
                stargazers_count = 0,
                watchers_count = "",
                full_name = "",
                description = null,
                html_url = "",
                owner = {},
                language = "",
                updated_at = "",
                id = "",
              } = item || {};
              const { avatar_url = "", type = "" } = owner || {};
              const info = {
                stargazers_count,
                watchers_count,
                full_name,
                description,
                avatar_url,
                type,
                html_url,
                language,
                updated_at,
              };
              return <RepoCard info={info} key={id} />;
            })}
        </div>
      </div>
    </>
  );
}
